[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/resume.pdf"
  to = "/Telmah_Tantoh_Software_Engineer_Master_Resume.pdf"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
